import React from 'react'
import './DescriptionBox.css'

const DescriptionBox = () => {
    return (
        <div className='descriptionbox'>
            <div className="descriptionbox-navigator">
                <div className="descriptionbox-nav-box">Description</div>
                <div className="descriptionbox-nav-box fade">Reviews (122) </div>
            </div>
            <div className='descriptionbox-description'>
                <p>
                    JavaScript is a dynamic computer programming language. It is lightweight and most commonly used
                    as a part of web pages, whose implementations allow client-side script to interact with the user and
                    make dynamic pages. It is an interpreted programming language with object-oriented capabilities.
                     JavaScript was first known as LiveScript, but Netscape changed its name to JavaScript, possibly
                    because of the excitement being generated by Java. JavaScript made its first appearance in
                </p>
                <p>
                    JavaScript is a dynamic computer programming language. It is lightweight and most commonly used
                    as a part of web pages, whose implementations allow client-side script to interact with the user and
                </p>
            </div>
        </div>
    )
}
export default DescriptionBox